export enum WarningCodes {
    THREAD_ALREADY_ACTIVE = "#THREAD_WARNING_0001",
    THREAD_ALREADY_INACTIVE = "#THREAD_WARNING_0002",
}

export enum ErrorCodes {
    THREAD_INVALID_SIMULATION_UPDATE_RATE = "#THREAD_ERROR_0001",
    THREAD_INVALID_DELTA_TIME = "#THREAD_ERROR_0002",
    NUMBER_NO_VALID_INPUT_PROVIDED = "#ARRAY_NO_VALID_INPUT_PROVIDED_0001",
    WGPUR_CANVAS_NOT_CREATED = "#WEBGPU_RENDERER_CANVAS_NOT_CREATED_0001",
    WGPUR_API_NOT_SUPPORTED = "#WEBGPU_RENDERER_API_NOT_SUPPORTED_0002",
    WGPUR_UNABLE_TO_GET_ADAPTER = "#WEBGPU_RENDERER_UNABLE_TO_GET_ADAPTER_0003",
    WGPUR_INVALID_DPR_VALUE = "#WEBGPU_RENDERER_INVALID_DPR_VALUE_0004",
    WGPUR_DEVICE_UNCAPTURED_ERROR = "#WEBGPU_RENDERER_DEVICE_UNCAPTURED_ERROR_0005",
    WGPUR_DEVICE_LOST_ERROR = "#WEBGPU_RENDERER_DEVICE_LOST_ERROR_0006",
}