export enum WarningCodes {
    THREAD_ALREADY_ACTIVE = "#FLUENTGL_WARNING_0001",
    THREAD_ALREADY_INACTIVE = "#FLUENTGL_WARNING_0001",
    WGPUR_HIGH_DPR_VALUE = "#FLUENTGL_WARNING_0003",
}

export enum ErrorCodes {
    THREAD_INVALID_SIMULATION_UPDATE_RATE = "#FLUENTGL_ERROR_0001",
    THREAD_INVALID_DELTA_TIME = "#FLUENTGL_ERROR_0002",
    NUMBER_NO_VALID_INPUT_PROVIDED = "#FLUENTGL_ERROR_0003",
    WGPUR_CANVAS_NOT_CREATED = "#FLUENTGL_ERROR_0004",
    WGPUR_API_NOT_SUPPORTED = "#FLUENTGL_ERROR_0005",
    WGPUR_UNABLE_TO_GET_ADAPTER = "#FLUENTGL_ERROR_0006",
    WGPUR_INVALID_DPR_VALUE = "#FLUENTGL_ERROR_0007",
    WGPUR_DEVICE_UNCAPTURED_ERROR = "#FLUENTGL_ERROR_0008",
    WGPUR_DEVICE_LOST_ERROR = "#FLUENTGL_ERROR_0009",
}