export enum WarningCodes {
    THREAD_ALREADY_ACTIVE = "#THREAD_WARNING_0001",
    THREAD_ALREADY_INACTIVE = "#THREAD_WARNING_0002",
}

export enum ErrorCodes {
    THREAD_INVALID_SIMULATION_UPDATE_RATE = "#THREAD_ERROR_0001",
    THREAD_INVALID_DELTA_TIME = "#THREAD_ERROR_0002",
    NUMBER_NO_VALID_INPUT_PROVIDED = "#ARRAY_NO_VALID_INPUT_PROVIDED_0001",
}